import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,version,isUnread,sinceLastCheck,selectItems,acknowledge,validItem} from '../domain.mjs';
const item={id:'a',title:'Dify リリース',url:'https://example.org/a',sourceName:'Dify',category:'ai-dev',importance:80,detectedAt:'2026-09-09T03:00:00Z',updatedAt:null,revision:1,tags:['更新']};
test('read articles become unread when updated',()=>{const state=initialState();state.read.a=version(item);assert.equal(isUnread(item,state),false);assert.equal(isUnread({...item,revision:2,updatedAt:'2026-09-09T04:00:00Z'},state),true);});
test('checking uses dataset watermark, not wall clock',()=>{const state=acknowledge(initialState(),[item],'2026-09-09T03:00:00Z','2026-09-09T05:00:00Z');assert.equal(sinceLastCheck(item,state),false);assert.equal(sinceLastCheck({...item,updatedAt:'2026-09-09T04:00:00Z'},state),true);assert.equal(isUnread(item,state),false);});
test('category, keyword, hidden, unread and importance filters compose',()=>{const other={...item,id:'b',category:'game',title:'Event',importance:40};const state=initialState({category:'ai-dev'});assert.equal(selectItems([item,other],state,{query:'DIFY'}).length,1);state.hidden.a=true;assert.equal(selectItems([item],state).length,0);assert.equal(selectItems([item],state,{hidden:true}).length,1);assert.equal(selectItems([other],initialState(),{view:'important'}).length,0);state.hidden={};state.unread=true;state.read.a=version(item);assert.equal(selectItems([item],state).length,0);});
test('saved article survives server retention and uses fresh revision',()=>{const state=initialState({saved:{a:item}});assert.equal(selectItems([],state,{view:'saved'}).length,1);assert.equal(selectItems([{...item,revision:2}],state,{view:'saved'})[0].revision,2);});
test('malformed local state and unsafe feed entries',()=>{assert.deepEqual(initialState({read:'oops',saved:null}).read,{});assert.equal(initialState({cutoff:'invalid'}).cutoff,null);assert.equal(validItem(item),true);assert.equal(validItem({...item,url:'javascript:alert(1)'}),false);});
